/**
 * Downloads the curated Valorant art set and the self-hosted webfonts.
 * Run once: `npm run assets`. Everything lands in public/img and public/fonts,
 * so the site never depends on a third-party CDN at view time.
 */
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const IMG = path.join(ROOT, 'public', 'img');
const FONTS = path.join(ROOT, 'public', 'fonts');
const API = 'https://valorant-api.com/v1';

// Clove is her main, so Clove leads the roster and carries the hero art.
const MAIN = 'Clove';
// Agents whose art is used in the roster strip and the parallax scenes.
const ROSTER = ['Clove', 'Jett', 'Sage', 'Killjoy', 'Neon', 'Raze', 'Reyna', 'Phoenix', 'Omen', 'Sova'];
// Agents whose full portrait carries a hero composition.
const HEROES = ['Clove', 'Jett', 'Sage', 'Neon'];
// Maps used as far parallax layers.
const SCENES = ['Ascent', 'Haven', 'Lotus', 'Sunset', 'Breeze', 'Icebox'];

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-');

async function getJSON(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return (await res.json()).data;
}

async function download(url, dest) {
  if (existsSync(dest)) return 0;
  const res = await fetch(url);
  if (!res.ok) {
    console.warn(`  skip ${path.basename(dest)} (${res.status})`);
    return 0;
  }
  const buf = Buffer.from(await res.arrayBuffer());
  await writeFile(dest, buf);
  return buf.length;
}

async function fetchArt() {
  await mkdir(IMG, { recursive: true });
  const [agents, maps] = await Promise.all([
    getJSON(`${API}/agents?isPlayableCharacter=true`),
    getJSON(`${API}/maps`),
  ]);

  const jobs = [];
  const palette = {};

  for (const name of ROSTER) {
    const a = agents.find((x) => x.displayName === name);
    if (!a) continue;
    palette[slug(name)] = {
      name: a.displayName,
      role: a.role?.displayName ?? 'Agent',
      gradient: (a.backgroundGradientColors || []).map((c) => `#${c.slice(0, 6)}`),
    };
    jobs.push([a.displayIcon, path.join(IMG, `agent-${slug(name)}-icon.png`)]);
    jobs.push([a.background, path.join(IMG, `agent-${slug(name)}-bg.png`)]);
    if (HEROES.includes(name)) {
      jobs.push([a.fullPortrait, path.join(IMG, `agent-${slug(name)}-full.png`)]);
    }
  }

  for (const name of SCENES) {
    const m = maps.find((x) => x.displayName === name);
    if (!m) continue;
    jobs.push([m.splash, path.join(IMG, `map-${slug(name)}.png`)]);
  }

  // Her main's real ability icons, used as the dossier kit on the briefing page.
  const main = agents.find((x) => x.displayName === MAIN);
  const kit = (main?.abilities ?? [])
    .filter((ab) => ab.displayIcon)
    .map((ab) => {
      const key = ab.slot.toLowerCase();
      jobs.push([ab.displayIcon, path.join(IMG, `ability-${key}.png`)]);
      return { slot: ab.slot, name: ab.displayName, icon: `img/ability-${key}.webp` };
    });

  let total = 0;
  for (const [url, dest] of jobs) {
    if (!url) continue;
    total += await download(url, dest);
  }

  const roster = ROSTER.map((n) => palette[slug(n)]).filter(Boolean);
  await writeFile(
    path.join(ROOT, 'public', 'js', 'agents.js'),
    [
      "// Generated by scripts/fetch-assets.mjs. Names, roles and Riot's own gradients.",
      `export const MAIN_AGENT = ${JSON.stringify(palette[slug(MAIN)], null, 2)};`,
      `export const MAIN_KIT = ${JSON.stringify(kit, null, 2)};`,
      `export const AGENTS = ${JSON.stringify(roster, null, 2)};`,
      '',
    ].join('\n'),
  );

  console.log(`art: ${jobs.length} files, +${(total / 1048576).toFixed(1)} MB downloaded`);
}

async function fetchFonts() {
  await mkdir(FONTS, { recursive: true });
  const href =
    'https://fonts.googleapis.com/css2?family=Big+Shoulders+Display:wght@500;700;800;900&family=Barlow:wght@400;500;600;700&family=Share+Tech+Mono&display=swap';
  const res = await fetch(href, {
    headers: {
      // Modern UA so Google serves woff2 rather than legacy formats.
      'User-Agent':
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36',
    },
  });
  let css = await res.text();
  const urls = [...new Set(css.match(/https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2/g) || [])];

  let n = 0;
  for (const url of urls) {
    const file = `${url.split('/').slice(-2).join('-').replace(/[^\w.-]/g, '')}`;
    await download(url, path.join(FONTS, file));
    css = css.split(url).join(`../fonts/${file}`);
    n += 1;
  }
  await writeFile(path.join(ROOT, 'public', 'css', 'fonts.css'), css);
  console.log(`fonts: ${n} woff2 files self-hosted`);
}

await fetchArt();
await fetchFonts();
